### ISSUE TITLE
Throwing an error I can't find answer to

### ISSUE THREAD

**Issue by misterdwood** [mlvnt/deviantart-scraper#1]
Hey man,
   I love the idea, was wondering if you could help me out with the issue i'm having.  I have cloned it, and had to make one change for it to work somewhat, and I keep solving what issues I run into, but i got stumped with this one.  After running it, i get chromium to open, and it pulls the right number of unique files, but then it errors out here: 

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/deviantart-scraper/devianart.py", line 183, in worker_thread
    p = get_full_image(link)
  File "/home/pi/deviantart-scraper/devianart.py", line 116, in get_full_image
    download_now(req,title)
  File "/home/pi/deviantart-scraper/devianart.py", line 159, in download_now
    name = name_format(url,title)
  File "/home/pi/deviantart-scraper/devianart.py", line 149, in name_format
    p2 = name.split('-')[1].split('.')[1]
IndexError: list index out of range

I did have to take out the "chrome_options=options" part on the Chrome driver call.  But other than that, I have it exactly how you made it.  Let me know if you can give any help. 

Thanks!

**Comment by mlvnt** [comment]
Sorry for the late reply. As it sais the IndexError means that probably we got an empty array or out of range (the name is not found). Deviantart changed a lot since I wrote this script and that causes most of the issues now. Will be updating it soon and adding a lot of goodies such CLI interface.
