### ISSUE TITLE
I am unsure what I am doing wrong

### ISSUE THREAD

**Issue by hypr2020** [mlvnt/deviantart-scraper#2]
it seems to error out when I run the script. I am unsure if I am missing any info in the script or not.

Traceback (most recent call last):
  File "devianart.py", line 224, in <module>
    main()
  File "devianart.py", line 199, in main
    get_thumb_links(tasks) # Fill the Queue
  File "devianart.py", line 52, in get_thumb_links
    d = get_driver()
  File "devianart.py", line 38, in get_driver
    driver = webdriver.Chrome(options)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\subprocess.py", line 1247, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\subprocess.py", line 549, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 816, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not Options

**Comment by mlvnt** [comment]
Hi @hypr2020 , looks like a webdiver issue:

```python
File "devianart.py", line 38, in get_driver
driver = webdriver.Chrome(options)
```

The `webdirver.Chrome()` expects keyword arguemts only. A valid webdirver instance will be something in the lines of  `webdirver.Chrome(chrome_options=<the options var>)`. The options variable should be an instance of `webdriver.ChromeOptions()` to which you add your options. Here's a snippet from the script

```python
options = webdriver.ChromeOptions()
options.add_argument('--headless')
driver = webdriver.Chrome(chrome_options=options)
```

If you don't want to pass any options the driver can simply be

```python
driver = webdriver.Chrome()
```
